    label day_2:

    "It felt like a stream of endless colors tainting my vision.  My dream consisted of all kinds of unknown figures, beasts, and random memories, all mixed together like a soup that was about to start boiling."
    "Everything went quiet. A deafening silence was followed by an abyss that swallowed all my senses. Maybe everything was so quiet because I had been swallowed, gobbled up by some kind of monster."
    "My senses started to disintegrate as if I were being dissolved in some kind of gastric acid. I was uncertain of the nature of my current state of being."
    "I tried to look at my surroundings. Maybe something happened when I lost control of my senses. I could finally see better — if you can call this sight. I smelled an awful metallic stench preparing me for something worse to come."
    "A broken expectancy told me this place was nothing like home, or anywhere for that matter."
    "As I immersed myself even more into it, the abyss turned into walkable ground, with a smooth yet oddly harsh texture — nothing like silky cloth or a rocky mountain. The sensation was impossible to put into words."
    "I looked down to see my nude body, but shame didn’t wash over me. Instead, I felt a familiar warmth, unlike any other temperature, somehow mixed with emotions. My fur felt damp after a few seconds of staring at my birthday suit."
    "Suddenly, it was all stripped from me. A piercing gust of cold isolated me from the rest of the place. This place seemed not to desire me, as if it were rejecting me.  It was as if it wanted to vomit me into somewhere else, like I never belonged here while disguising it with care and gentleness."
    "I started running from somewhere or someone. I feared perhaps I was dead or maybe hadn’t come into existence just yet."
    "Over and over again, this period marked my independence, from inside to outside, from warmth to cold, from one to two."
    "I tried not to delve much into the eeriness this strange place offered me, though it was such a unique experience. Castles atop giant mountains revealed the truth of my presence. I was a mere ant, so small, I could be ignored."
    "Yet I tried to climb the mountain. Maybe it stood far above the clouds, but eventually I finally reached the gates.  I honestly didn’t know I could walk or swim  perhaps in such a rapid manner."
    "I felt small, tinier than a speck of dust. The gates opened upon my presence, but maybe it wasn’t for me; maybe it was for someone else, so I waited. I waited until it dawned on me that it was better to enter and delight myself with the giant banquet they must’ve put together for everyone."
    "Down in the halls, the walls seemed to tell a history—an untold history of eons ago, when things were just beginning. Over and over, I passed through tapestries that revealed the agony of many."
    "I couldn’t understand the reason why they were there, but then I heard something."
    "Still unclothed, I clung to one of the tapestries with an intricate pattern, trying to cover my shame with it."
    o "Your misbehaving has tainted your image, and your presence is no longer welcome in my humble abode."
    o "Must I need to make this even more clear than the finest and most perfect grain of diamond in the universe?"
    o "You will fail and bring forth disappointment. My father is also your progenitor, by extension. A heavy hand will fall upon you."
    l "Challenging with fine prose won’t lead me astray from my own goals. I have already won the game, and you were only the provider for the means of my game."
    o "You make yourself greater, but it\'s not a game to begin with."
    o "Toiling with their existence can cause greater harm to them."
    l "Shut up. I don’t come up here for perception and clarity."
    l "I’m already broken from the disappearance of my brother, our brother."
    o "He’s gone because you failed once, and you will fail twice."
    l "And yet you private me from the truth…"
    o "If truth is what you seek, then the truth you shall get. At last, just leave me the fuck alone."
    o "Adamu has strayed from the path I have weaved, and now I fully support his decision. However, it is with great sadness that he’s no longer with us."
    l "So, Adamu, the Apostate. It wasn’t just a joke that echoed through this place? It’s real, and I still ain’t satisfied."
    o "What, you plan on bringing him forth again from whatever state he may have turned into?"
    l "I don’t care what Adamu did or does. I only cared for him while he was by my side."
    l "I haven\'t heard of him in eons after our first encounter following the formation of our plan."
    l "But you treat me with unprecedented disrespect as if I wasn\'t from the same order as you."
    o "Your offense has worn me out…!"
    "An earthquake reverberated through the entire castle, as if it were dismantling, and so the pillars shifted and bent to form shapes, which repeated on themselves like they were mirrored or repeated."
    "The tapestry covering my jewels had been lifted. I started to lose my balance once I noticed a roll of pillars coming my way."
    "I had to flee, but before doing that, I saw them both looking directly at me or maybe past me. A paw grabbed the being that looked to be made out of stars by the giant one that looked like a rock with thousands of symbols in boiling red."
    "I closed my eyes to prepare for the incoming giant hands… but nothing happened."
    "Instead, I felt as if sharp blades of cold were piercing through my skin… I was falling, much to my disgrace.  When I was about to hit the ground, bracing myself tightly, I was jolted from my dream.  In spite of all efforts to make myself more comfortable, the little to no space given to me in my slumber was incredibly tiny."
    "Still, I figured out it would be better if Miq spent the night in a more comfortable manner since he must’ve had a long train trip."
    "As soon as I thought of what his travel must have been like, a chilly sensation brushed against my fur.  Once the morning light rays slapped my eyes, it was almost identical to what I felt yesterday, in the same order of events, but this time his bed was…"
    "Empty. Devoid of the white fluffy mountain that inhabited my bed yesterday night, only a few strands of his fur matted my sheets. I wasn’t expecting him to be gone so early. Maybe he just went for a morning jog? Wasn’t he on vacation?"
    "I directed myself to the bedroom door, which was left ajar. I heard sounds coming from the kitchen, and the smell of fried eggs made its way to my nostrils. I was not really used to the idea of being woken up by someone else."
    "I found him wearing an apron, still half naked, preparing breakfast for both of us. " "It was cute in a way, but I got slightly worried that he might’ve needed to go to the nearest store to buy some more…"
    "Shit!"
    "I didn’t finish stocking everything and moving all the boxes. Mr. Sorim is going to skin me alive!"
    "Quickly trying to fetch the nearest and cleanest towel available in my bedroom, I quickly took a shower. I suddenly remembered I didn’t do laundry the other day, and so all my clothes were dirty."
    "Trying to think of a possible excuse to skip work today, I heard a knock on the bathroom door. It told me someone bigger was either purposefully trying to tear down my already creaking door or had lost control of his own force."
    m "Ahh, ani bes!?"
    "Again, that unknown language hammering through all my previous preconceptions of him echoes without ceasing in my mind. I shove the thought away once again and speak, trying to overpower the loudness of his voice and beating."
    e "I’m ok over here! No need to worry, Miq."
    m "Ok then."
    m "I’m frying some eggs over here, sweet."
    "That last word echoes through me like he said something completely, utterly unhinged, and yet I can\'t help but think it\'s so considerate of him.  It was perhaps a tad too early for a cute name exchange, though."
    e "Very well, I\'m coming out soon."
    "I was prepared to hurry up so that I would not miss breakfast with my big polar bear. After drying my fur, I quickly grabbed the cleanest set of clothes I had available."
    "I sat down at the kitchen table waiting for him, but when he turned around, I felt a tinge of disappointment. He placed two fried eggs in front of me, and a simple orange juice."
    "I tried to question his melancholic facade, but I figured it was because I simply lacked the skill to make my house more organized."
    "I should consider organizing my stuff later today, but checking on work is a priority."
    m "Today I didn’t receive a proper good morning from you! hehehe."
    e "Very well, you\'ve earned your good morning, my…?"
    m "Oh, don\'t worry about formality, right now or ever.  Let\'s just call ourselves whatever."
    e "Oh, I see, I thought you\'d be mad."
    m "No worries, sweet."
    "Again, it echoes through my mind, back and forth, creating a huge weight on me. Given the right circumstances, it might have looked fine, but now it sounds alien to my ears."
    "I wanted to rip my ears apart every damn time he said those words, and yet, it felt genuine, like I was really in for a win."
    "Finally, I\'ve found someone of my liking. And he\'s even a professor at an amazing university."
    "As the last spoonful of breakfast enters my mouth, I am reminded of my job, tormenting my mind again with a myriad of intrusive thoughts. I consider possibly quitting it for the sake of my sanity."
    "Mr. Sorim abused his staff as much as he liked, and I am his primary target. ""Thankfully, he\'s too old to go to the store’s lower floor very often."
    "Coming back to an empty plate, the polar bear seemed happy to touch my fur, but once I noticed his enjoyment, he quickly switched to a more serious demeanor."
    "I was once again prompted to go about my day, but this time, it was different. He was with someone else. Could we already be considered boyfriends?"
    "No, no, this is getting out of control. ""We\'re just very friendly with each other."
    "I wouldn\'t mind skipping my job once again.  After all, my big polar bear cannot be left unattended to wander astray!"
    m "Hey, were you expecting a letter?"
    m "I pretty much believe those are things from the past, not that I\'m very aware of how technologically adept you guys are-"
    e "Nah, throw it away. There\'s always someone putting trash in my mailbox."
    e "They even have the audacity to put on falsified stamps."
    m "If you say so."
    "Taking the letter off the ground…"
    # [Never mind…] 
    "Crushing it into a ball of paper, I noticed there was something oddly different this time."
    "Other than the clear lack of a falsified stamp, or any stamps for that matter, the envelope seemed to be flimsy, and its contents were scattered everywhere."
    "I paid no attention, though, as Miq opened the door to reveal this peculiar place. It was always roughly the same climate and temperature."
    "Mr. Sorim’s other favorite pastime is amateur meteorology. He believes this city is plagued with a curse that will not be lifted until something dramatic happens."
    "I\'m indifferent to his claims, whether or not they\'re true.  Everyone likes this weather, and agriculture was never affected, so why bother?"
    "I\'ve forgotten the meaning of heat waves or the warmth of the sun\'s rays because every day, I\'m bathed in such faint light that escapes from the abrasive embrace of the clouds."
    "Miq pushed me out of my trance, which blurred reality into a confusing mess of memories and contemplation—something I\'ve become used to in the last years or so."
    "He snapped me back to reality."
    m "So, today, we don\'t have much planned unless you know of any museum or library with the city\'s history."
    e "We do."
    e "We were by the municipal museum’s park yesterday… When you took your shirt off…"
    "Ignoring the last bit of uncomfortableness in my speech pattern, I thought of the possible horrible outcomes of being seen with a half-naked guy, and whether it would lead others to think worse of me…"
    m "Ah, that\'ll do."
    m "Let\'s be off then and not delay any more."
    e "On it!"
    "Leaving the house wasn’t an arduous task. What was challenging was how I would deal with Mr. Sorim, but that was for another time."
    "Walking by his side was our most distressing yet comforting activity so far. Ghosts populated this place, and the deafening silence was a stark, yet notable characteristic."
    "Maybe forgotten by God was the best description someone could give to this town. Even the local priest was somehow always absent.   Mr. Sorim’s brother, F. Reven was even more distressed than his brother."
    "At least F. Reven was always busy commuting with God in whatever macabre seances he must perform in the church\'s sacred soil."
    "Swiftly returning to reality, I recalled all the times I found myself daydreaming just today — more than ten times already — of possible scenarios and unattainable results."
    "I once did the same path a few months ago to check on my personal documents, but now Miq was leading the way. He told me he had a town map on the way, yet curiously he had asked me about the museum…"
    "The institution stood firm, its weathered facade bearing the passage of time. Some features had been remodeled over the years whenever extra funds were generously donated to it."
    "It was one of the few places in town with telephones and computers, but I barely used them. Books were still the most reliable for most of my research…"
    "Whatever Miq’s research may be, I’m here to support him in every possible way."
    "Arriving at the museum, I noticed he began scratching his chin and shoulders in a worrisome way.  I wanted to ask him if everything was ok, but hid my face in response to his thundering speech towering over all the other sounds."
    m "Very well."
    m "I hope we may find all the necessary documents to dissect what this town has to offer."
    "Walking down to the reception, Miq tried to soften his voice to no avail."
    m "Good morning, ma’am. May I please be directed to the town’s historical records and possible maps?"
    "The lady swiftly tilted her head to take a better look at us, examining our features."
    "Finally, she sighed and started typing something, presumably looking in the records of the library."
    Receptionist: "It\'s on wing Q34, a bit further back on this floor. Enjoy your reading."
    m "Thanks!"
    "Rushing through the disarray of unpacked boxes covered in years of thick layers of dust made searching even more unbearable. I was coughing like hell, and I couldn’t keep my nose away from it. I started sneezing uncontrollably."
    "After switching between sitting and standing to pick up and return books, a single hardcover stood out to me. It was a book Miq had shoved to the side in hopes of finding something even more useful for his research…"
    "He never told me what he was looking for exactly, a topic so elusive, he didn’t mention it to me until now.  I thought it was a bit strange after the time we had spent together recently."
    "Regardless, I was sure he would eventually tell me about his research, whether or not it mattered for me to know it."
    "Upon returning to the book that lay open on the desk just a few inches from me, I sat down and started to flip some pages, perusing it to make sure we didn’t miss something important."
    "Something caught my attention. This book seemed strange, unlike the others. I looked at the cover, but it had no title. It contained only handwritten pages, similar to a journal, but Latin was plastered all over it. I couldn’t decipher it, so I thought about asking Miq."
    "Suddenly, a strong wind forced the windows open, followed by heavy downpour without warning. Each heavy drop of water begged to be heard, so closing the old rusty windows was imperative."
    "Thunder followed.  A storm was forming outside, growing more intense by the second. It seemed as if someone called upon the four winds to blow and shatter."
    "From another opened window, pages of the ever-mysterious book I was trying to focus on flipped furiously, revealing a myriad of strange patterns I had yet to analyze."
    "The receptionist rose from her seat to quickly close all the windows, including the one responsible for the gust that furiously flipped through the pages of the strange book."
    "Upon close inspection, the page it landed on was almost mesmerizing, different from any painting I’d ever seen."
    "Akin to a Renaissance painting… No, more like one of those books on occultism with hundreds of ciphers. The book proudly displayed its most confusing page to me, elusive of meaning."
    "I paid no attention as time passed.  I kept exploring every crevice of that image, probably printed page by page with Gutenberg’s invention and distributed only by the most secretive societies of the age, somehow ending up here."
    "A white fur paw passed in front of my muzzle, attempting to bring me back to reality, but my brain barely registered it."
    m "Hey, bookworm, you’ve been staring at this page for half an hour."
    m "You good, sweet?"
    "His speech jolted me from my self-induced trance. I finally began to reassess my surroundings. It seemed nothing changed apart from a few more books being opened or closed."
    m "Erin?'
    e 'Oh, hi, I just-"
    e "Well, this book was so interesting.  I think I lost track of time…"
    "Looking rather disheveled of self awareness and still doubting my half-assed excuse, he decided to play along."
    m "*Sigh* Right…"
    m "Shall we go back to your home? I’ve gathered enough data about this town and its history-"
    e "Wait, wait, what about this book right here?"
    "Looking at the book, the page I’ve been staring at for the past hour had vanished, along with all of the intricate drawings, and the message behind it."
    "It was gone, replaced by a poem:"
    # Overtaken by guilt,
    # Pierced by their hollow labor.
    # Mirror of the soul,
    #  Yearns for the pure gesture.
    # Shrouded in darkness,
    #  Washed, bleached of their colors.
    "Trying to seek meaning through words that. seemed more like a spell, I became thoroughly disappointed."
    "Did I just imagine that? What the fuck is this?"
    "Being pulled out of my mind again by this puzzling book, I close it and toss it over the table in an act of primitive rage or perhaps dread. The scariest thing about the book was knowing it had a beautiful pattern that soon faded away in the blink of my eyes."
    m "Hey, hey, big boy."
    m "No need to toss it away."
    e Right, sorry. I just saw something scary flash before my eyes.
    m "Hmm, whatever is was, we need to be off. There’s no time for babbling. I heard people were in danger."
    e "Oh really? Why, though?"
    m "Jeez, you\'ve been so immersed in this book you missed the storm outside."
    e "Well, I guess it’s to be expected. I\'m already used to storms."
    m "I don\'t know how you weren’t aware of it. That storm was enormous and scary even if you wanted to deny it."
    m "Come on, sweet, we should see if anyone\'s in danger."
    "Gripping on my paw, he pulled me towards the main aisle and through the entire library, swinging me like a ragdoll and taking notice of all of my movements."
    "The outside came like a blinding light, and puddles were everywhere. As a result of windy rain, there were more branches, leaves, and debris than usual."
    "A few sirens followed by loud screens of desperation were heard all across the street."
    "W: Where\'s my boy!?"
    "W: He left home this morning but hasn\'t returned yet."
    "A police officer approached her on the verge of hyperventilating, reaching for air as if she was containing her panic attack."
    "As the truth started to settle down on her, what once were desperate yells of a mother looking for her missing son turned into streams of tears by the unsettling truth that her son was gone."
    "I tried to make sense of the almost theatrical scene that just played out before me."
    "Someone should tell me what happened."
    "Wishing no one had been hurt other than the little boy, the mother was still crying for her loss."
    "I wish no more tragedies would hit this town, even though those words were pointless to utter in my mind."
    "Waiting for… Answers. Real answers."
    "Answers about all the events that had unfolded in the last days or so made me feel I\'ve only just started living. Everything before this storm fading away like the disappearing contents of the book. Miq and…	"
    "Nemmi!"
    "No, that cannot be."
    "Over the corner of my eyes, I noticed a familiar face, such a familiar face that I haven’t seen in a while, but I was stunned and mortified to see him."
    "No, no, no, no…"
    "Tears started to blind me the more I staredI   realized I had broken my promise to go with him today, to talk to him, to be with him."
    "My legs gave way beneath me, and I fell to the ground, begging for this bad dream to end.  Whatever happened, it couldn’t be real."
    "And yet, there he was, lying on his back, soaked in muddy water and the cold embrace of death."
    "I wasn’t prepared for this. I wasn’t even prepared for when my own father died. I hid myself in my shell and shoved the reality away."
    "But suddenly, death felt more than real; it pierced me through from one end to another.  As I was now kneeling down on the wet pavement, my tears mixed with the dampness."
    "Why did it have to be like this? This was never supposed to happen. Why, why, why?"
    "A pound of white fur rested just above my head, caressing me. It sort of comforted me as I looked up and saw Miq also shed a tear for my now-deceased friend."
    m "Can we go back home? I gather he’s important to you, but it\'s probably better to leave."
    "Rising from my ball of sadness, I wanted to scream off the top of my lungs, take Nemmi, and try to revive him. Yet it was too late."
    "It was too late to do anything.  Too late to talk to him. Too late even to hug him."
    "…"
    "For the rest of the day, I went home to rest and make sure nothing was water damaged."
    "Some homes were completely flooded by the heavy storm that assaulted us today."
    "I collapsed on the bed in my room, while Miq decided to stay in the living room, sorting his own stuff and checking his small black slate. What was it, he called it again? A cellphone. He told me that thing was basically his entire life; he couldn’t go anywhere without it."
    "I tried to imagine someone living with that thing attached to their body, but all my thoughts were clouded by the realization that I’d broken the most basic rule of promises: never break a promise."
    "Tears resurfaced when I sat up on my bed. Hyperventilating, all my memories come back to haunt me once again, memories of me and Nemmi playing in the playground, even though we were the only children then."
    "Gone were those precious days that I shoved away in favor of my dead-end job and this polar bear who doesn’t even know me and who I fucked for nothing but pure carnal pleasure."
    "The more the truth dawns on me, the more I notice how badly I messed up, how terrible I must’ve looked yesterday when I rejected Nemmi."
    "My friend, Nemmi, whom I so dismissively put away."
    "I’m an idiot, the greatest idiot ever lived."
    "I bash my own bare paws against my head, repeating the self-deprecating mantra while crying. I began tearing at my fur; I don’t even deserve to be seen by the mirror."
    "I fell on my bed and tried my best to subdue my helpless sobbing. Miq, on the other paw, barely acknowledged I was crying."
    "Does he ever care, other than calling me sweet and cute occasionally? Is he even someone I like? Do I like him? Am I just a touch-starved selfish bitch?"
    "In a rampage of stress, anxious and wrathful thoughts come like a powerfully strong torrent."
    "I lost Dad, I lost Nemmi, so now I don’t need to lose Miq. He’s the last bit of safety and warmth I’ve felt recently. Even though he\'s dismissive and perhaps only superficially likes me, I must keep him by my side."
    "Wiping away my tears and doing my best to rise from the bed, I decided to do one thing... To wake up Miq and kiss him, like we did the first time together."
    "Approaching the sofa where he lay with his chest exposed, I decide to also remove some clothing, and then reaching out to him, I start to stroke his chin and then his white belly, expecting him to wake up, but there was nothing. He doesn’t even budge."
    "An awkward silence makes up for the next couple of seconds. I ceased to pat him, and as if on cue, his slumber got heavier by the second. I chose instead to plant a kiss on his cheeks."
    "Suddenly, he jumped from the little scare."
    m "Uhh… Earhh, Wot?"
    e "Sorry, sorry, I just wanted to wake you up."
    m "For what?"
    e "I just wanted to cuddle a little bit before going to bed."
    e "With everything that happened today, I figured out you’d also want-"
    m "What…Oh, ok; yeah."
    m "I’m sorry for your loss. He must’ve been a great friend."
    e "Hmm, ye."
    e "Sorry, I don’t know if I\'m in the mood for this, but I just wanted a distraction."
    m "Hey, whatever you want to do I’m down."
    e "What about… a conversation?"
    m "Sure."
    "Snuggling even more to his build, I sigh, indicating the tiredness of what a day today was."
    e "Soo, what made you so interested in this town?"
    m "Hmm, that is, hmm…"
    m "For my final thesis in anthropology, I wanted to conduct a study in an isolated village unaffected by 21st-century technologies."
    m "I kept searching villages all across the country, but nothing came of it."
    m "As you probably guessed by the use of my native language, I’m not even from this country."
    e "Ah, I’ve never heard your language before."
    m "You mean, Mihiq?"
    m "It’s the native language of my people."
    m "And though my name comes from Michael, in my community I’m named Pullisawaq Qimma Hupa, which can be just shortened to Qimma."
    m "It’s a name convention quirk of my people. We have different names depending on our position, and sometimes, some names become taboo to say aloud…"
    m "But back to the actual topic at hand..."
    "He waved his paws in the air, looking for words to get back to the main topic of our conversation."
    m "My anthropology thesis gave me just enough academic budget to visit a single place, but it was hard to find somewhere knowing today’s technology has already touched most places."
    m "I noticed your town was barely documented. It even lacked a proper telephone line. And that meant I found the sweet spot to start my research."
    m "However, the more I investigate your town, the less insight I get. It’s like this town is…"
    "Waving his right paw in a circular motion, looking for words again, and then closing it in a fist, reassuring he couldn’t be more than indelicate in this moment."
    m "Non-existent."
    m "It’s like this entire place was forgotten by the government, forever trapped in a trance-like state."
    m "Of everyone that once came here, it seems none ever came back."
    m "I’m not afraid that might happen to me, but I also want to stay here for a few more years to document all the possible strange anomalies that are going on here."
    e "Anomalies? You mean, our town is more than just isolated and rainy as hell?"
    m "Exactly."
    m "On top of virtually not existing in current records, your town doesn’t seem to be aware of anything that happens outside its borders."
    m "It’s like you guys are trapped in a sort of time-bending sphere."
    e "How so?"
    m "You guys have never been touched by the outside--"
    "I cut his speech as if I needed to contest him with the fact that I moved here just a few years ago."
    e "No."
    e "I mean, my family and I moved here a few years ago, and we’ve been here since March of 1957."
    "Upon hearing the number mentioned, Miq’s muzzle hung open, and his eyes widened. The single mention of that number, a mere fact to me, was enough to leave him speechless."
    "A disconcerting silence fell into the room like we were at the bottom of the sea, experiencing hundreds of bars of atmospheric pressure."
    "A dreadful and concerning facade painted his expression; he stood up, tidying himself up and buttoning up his shirt."
    m "What?"
    e "Look, it\'s not that bad is it?"
    m "What you’ve just said goes against time itself."
    m "Oh my lord…"
    m "Wait, how old are you?"
    e "I’m, uh, 19 years old."
    m "So that means we’re in 1962?"
    e "Correct, it\'s 11th November of 1962, at roughly 7 pm…"
    "I look at him like he is the crazy one here, the one asking all these weird details, when it\'s so obvious… There is a clear lack of what he calls the internet. I don’t even fathom how such a thing is supposed to work."
    m "Look. Tell me this isn’t a dream, and that I’m about to wake up in my bed in my dorm…"
    "I lose my composure and let my feelings angrily boil, like the single mention we’re in a fake scenario is somehow even worse than all the times he ignored me and shoved me away."
    "I stand up to be on his level."
    e "That’s literally impossible. This entire town, the death of my friend… and I, I can’t be fake."
    m "That’s not what I’m saying. You’re twisting it! I’m questioning the nature of this phenomenon."
    m "It’s not supposed to-"
    e "To what? What are you even talking about?"
    "Desperately stumbling around my living room, he looks for more clues to reveal the true nature of our time."
    m "Let me explain; please, can we sit down?"
    "Rubbing my temple in search of deep wisdom, since none can be found elsewhere. Miq\'s weird bad reputation to leave me out of things comes back again when he promptly gestured me to sit down."
    "We sit down on the sofa again, I, still shirtless, and he who was just started to unbutton his shirt again. He takes a deep breath and returns with a calmer voice tone to soften his speech."
    m "Ok, you believe we are in 1962."
    m "But we are not. That was 53 years ago."
    m "I didn’t know whether the entire town was playing a prank on me, celebrating a special remembrance holiday, or just genuinely looked like it was stuck in time."
    m "And everyone around here told me the same date. I didn’t believe them."
    m "But with it now coming from you, I cannot deny it any longer."
    "He took his cell phone out of his pocket and fumbled with the weird black mirror. It suddenly lit the entire living room, drowning both of us in a blue, penetrating light that hurt my eyes."
    "Showing me what looked like a calendar, the white background assaulted my vision making it even harder to look at it. But given time, my eyes to adjust to the sudden artificial light source."
    "There it was, a calendar showing me the following date: March, 15th of 2014."
    e "You modified it. There’s no way we are 53 years in the past. I would be even older than you!"
    e "I would be roughly 73 years old!"
    m "That’s what I’m talking about!  This goes against the very fabric of reality!"
    "Despite all the excitement that Miq exhaled, I was still sitting there trying to figure out why that was."
    "Shaking my head, I realized none of this made sense. Either Miq was crazy, or it was true, and I, along with the entire town, was tricked into believing it was trapped in 1962."
    "In denial, I repeatedly shrugged him off in small spasms and shook my head, expressing negation."
    e "It still doesn’t make sense. How an entire town is supposed to believe it’s trapped in the past for more than 50 years?"
    m "That’s the unanswered incognito conundrum. How."
    "Mouth gaping, Miq seemed to smile profusely at this simple realization."
    m "Somehow, this place, this exact town, existed in the past, meaning this is basically a time travel to the past!"
    "Trying not to reveal my utter skepticism shining through my eyes and serious expression, I let out a sigh that so much fails to hide my disappointment. Still, I decided to follow along and entertain his ideas."
    e "If that is true, then someone must be behind this hoax or call it time travel if that’s even possible."
    m "Yes!"
    m "Someone is behind this, someone with enough technological power to be able to-"
    m "Wait, what if this is a natural occurrence?"
    m "Have you ever noticed any plants that don’t belong to our current Holocene Era? Or even giant insects?"
    e "No? I don’t think so. I have never seen a prehistoric plant, regardless of its look-"
    m "Yeah, yeah, I figured that as much."
    "Three times, he jumped just like a toddler in glee, and he decided to take me and lift me."
    e "Hey, hey, haha, put me down, you silly!"
    "Ignoring my sudden change of mood he dances with me in his arms and teases as if he plans to kiss me on the forehead several times before we both collapse into my bed."
    "Once we are in a comfortable position, he still smiles like I’ve made something more than just existing to make him happy.  He finally reveals the motive behind the sudden movement."
    m "Erin…"
    m "You are probably the best thing that ever happened to my life."
    m "I love you."
    show black
    "There. Laying down in my bed, we both exchanged looks and caressed each other\'s fur, noticing our bodies\' texture and colors. Our eyes interlocked, like ponds that reflected our innermost sacred desires."
    "My own body felt foreign to me like silent bugs crawled under my skin and laid eggs that soon hatched in an infinite circle of eating me alive. My heartbeat resumed to something that hammered in my chest."
    "The atmosphere of the room felt heavier by the second, and each breath in and out felt almost like lifting hundreds of pounds, on top of being in such a vulnerable position."
    "I told myself many times, subconsciously ignoring those name-callings and affectionate touches…"
    "I should do something, but I feel as if my body is turning into stone and my stare ever so distant…"
    e "I love you too…"
    "And with that, I\'ve sealed my destiny."
    "Yes I loved him, but the fact we\'ve known each other for less than a week is disconcerting…"
    "But this might just be the way he expresses love and longing for someone."
    "So I follow suit, trying to harbor those feelings too as if I need self-reassurance as to why I should love him."
    "But I loved him!"
    "Right?"
    "…"

jump day_3