    label day_3:
        "The next day, I woke up as if nothing had happened last night, ignoring all the urges to scream or ignore the storm that formed in my mind and quickly went out."
    "I don’t remember if we did anything else. Maybe I blacked out, or we continued to talk. Maybe I retreated to the back of my mind."
    "Regardless, I was ready to go to work once again, but not before checking on Miq, who was weirdly rushing to take a bath. As soon as he left the bathroom, still in a bathing suit, he started cooking."
    "Still rubbing my sleepy eyes, I noticed I was barely clothed and sitting on the kitchen counter, waiting for the plate he had just placed in front of me."
    m "Hey, sunflower! Earth to Erin, do you copy?"
    e "Ahh, Hii~"
    m "Goood…"
    m "Anyway, today I’m preparing breakfast hehehe."
    "Still confused as to what happened last night…"
    e "Oh, fine, I guess, I mean."
    "Cleaning my throat, searching for words."
    e "I wonder where you found goodies?"
    m "I must confess I had canned food for days."
    m "Cooking canned food has always been one of the best survival skills I have acquired in the last few years…"
    m "Anyway, enough about me."
    "Suddenly, he leaned on the counter and closed his eyes. I thought to myself that maybe he was expecting something else, but then I snapped and kissed him."
    "Maybe an unrequired kiss, I didn’t mind it."
    m "You cutie, hehehe."
    m "You’re so precious…"
    m "You must be bored of this town, and like we talked last night-"
    e "What we talked about last night?"
    m "..."
    "Surprised at my sudden comeback, I thought it might be a bit rude to interject and interfere in his stream of thoughts, but I needed to make myself clear for once during this pretend dialogue."
    m "We talked about…"
    e "Tell me."
    m "I-"
    e "Ah, I’m sorry. I didn’t mean to sour the mood."
    m "It's okay, my sunflower…"
    m "We just… talked about some things like our relationship, how we were going to move onto the next step and things."
    m "I didn't want to rush you into taking matters even more seriously, but I really liked your initiative to express your sentiments in that way."
    m "I wasn’t exactly expecting you to be this flirty and forward."
    m "And I don’t know why you’re asking this, but no, we didn’t have sex last night."
    e "Right, oookayy…"
    e "Yeah, sorry for being quite paranoid…"
    e "I must’ve blacked out and forgotten most of our conversation…"
    m "Hey, it’s no biggie deal."
    m "Ah!"
    m "Sorry, that’s not all. I should tell you this as well, but I have a proposition for you!"
    "Pointing his index finger, he got ever close to my face as he extended the last word until he ran short of breath and coughed a little bit."
    m "Ehem..."
    m "Ok, this is going to sound crazy, but I tried to call my work colleagues from here. Surprise, surprise — well, it's not a surprise, but the signal worked…"
    m "…Once I got up a dangerously tall radio signal tower, at least."
    m "I discussed the anomaly with some of my colleagues and my mentor, and they absolutely exploded with joy and skepticism."
    m "But they trusted my judgment and wanted to discuss and see this town for themselves."
    e "Oh, that's interesting. So, will your final thesis be about this town?"
    m "Yes, but not quite? Let me think."
    m "No, but yes, but also no? Ok, let me explain."
    m "So, here’s the deal: I’ll need to go back to my campus and organize some of my life to convince my friends over the STEM major to come back with me and study this exact town, and it's time, wobbly things going on…"
    m "And so, I thought about inviting you to go back with me…"
    "Trying to process the huge amount of information given to me all at once, I try to concentrate on every corner of my kitchen."
    "My gaze goes to unreachable places, but I suddenly return to reality once I feel a touch up my shoulder."
    "With a worried expression, Miq tried to address this weird behavior of mine in a much more careful manner with gestures, but failing to communicate his concerns, he spoke."
    m "Hey, my sunflower. I’ve always wondered if this behavior of yours is normal. If so, it concerns me."
    e "Oh, it’s ok."
    e "Since childhood, I’ve had this annoying reaction to traumatic or overwhelming events."
    e "I can barely even remember the day my dad…"
    "I stop, immediately starting to fade away again, but this time, I get to stay conscious, in a sort of pseudo-aware state."
    e "Anyway, if I’m traveling, I should get ready."
    m "Hmmm…"
    m "Ok, ok, ok, ok…. O. K."
    m "Yeah, we should get ready."
    "Trying to examine his response as half-baked or not even a response made me quite uncomfortable."
    "I don’t know, but I should perhaps try to get communication going."
    e "Why did you take so long to say that?"
    e "Given how talkative you’ve been in the last hour or so, this seems a bit inconsistent with how you’ve been acting."
    "…"
    m "Hmm, yeah…"
    m "Fine, I’m sorry, but if you are to come with me, you must meet some requirements and maybe even change some things."
    "It shouldn’t be too bad to just change. Maybe this is to make us look more presentable and blend in more. But shouldn’t he support me regardless of manners and idioms?"
    e "Hm, what kind of changes?"
    "Maybe I can adapt."
    m "I’m thinking, hm…"
    "What if…"
    m "To make things work, we need to establish communication at all times, and it’s important to keep some thoughts to ourselves."
    m "Following this, you need a more modern that’s more suitable for 2014, given you’ve been stuck in time, we need to go shopping."
    m  "I wonder if the currency you have here has any current value…"
    e "Wait, why the first thing I need to change is communicating with you all the time?"
    m "We’ll be in the information era, my darling Erin.  You will be getting to use a real cell phone."
    e "Why would I need such a thing?"
    m "Trust me, you’re not mentally prepared to be dragged across more than 50 years into the future."
    e "Maybe."
    m "Great then."
    "Preparing to resume my cold and rather stale breakfast, I decided to put it away and simply start getting ready, packing things, and wrapping up everything I needed to get done."
    "His last response got me thinking a lot about it."
    "Should I go if it meant abandoning this town? I mean, maybe, but it wouldn’t change the fact that I would be abandoning all that I worked for, even if it meant just this house. And my friend… He’s gone, so it shouldn’t hold me back, but…"
    "No."
    "I can’t go with him. It would mean maybe discovering the hard truth, the very lie I’ve been holding onto, but I simply cannot leave!"
    "As much as I wanted to keep packing my clothes, listing my supplies, and thinking of how to notify my mother I was gone."
    "My arms stopped moving, and my gaze began to fall on another corner, preparing to turn off and perhaps spend several hours, or even days, stuck in this indefinite idling."
    "This time, I managed to fight against this urge and looked away. I felt the wind and the weak raindrops trying to speak to me, but they soon halted to mask the fake nature of everything around me."
    "After the strange episode, I thought to myself, remembering a crucial fact."
    "I should stay and see if Nemmi’s mother is doing fine after the loss of her only child… Besides, I want to be at his funeral and have a proper goodbye."
    "After gathering enough courage, I convinced myself that staying was the best course of action, given that the storm probably hurt other families."
    e "Miq... I-"
    m "Hm?"
    m "You're already packed? You’re so quick, hehe."
    m "And that is why I love y-"
    e "I cannot go."
    m "What?"
    m "No, you told me you would go with me, even if it meant giving up on a few things."
    e "I mean, changing my manners and attire is one thing, but this whole thing feels like an arrangement for disaster."
    e "I like you, Miq, I really do."
    e "But if we want to make this… us, and this travel to work, you need to give me time."
    m "Ok, I understand your reasoning."
    m "But never forget, I’m here for you, and if I can’t be by your side, this means you and this town..."
    m "Something bad could happen."
    "..."
    e "Something really bad happened yesterday, and I’m staying to help my folks..."
    m "Ah, very wise, but it still doesn’t make me less worried."
    m "In fact, I almost want to stay too, but I’ve devoted myself so much to this task that I'm leaving it all behind…"
    m "I can’t."
    "An incommensurable pit of darkness grew on my chest. Those last words said aloud felt almost like they put a huge weight on me."
    "I can’t afford to lose one more person… Not again, but this time there’s again, something preventing me from doing anything to impede me."
    "..."
    "Time seemed to warp once again, and again, and again, and again…"
    "Two hours after our little conversation, he was ready to go, and the train he once came out of was there once again, waiting for him to leave my town."
    m "So, is this a goodbye?"
    e "I guess so…"
    m "Don’t worry, I’ll be back..."
    "Walking into the train with a heavy trench coat, he examines the insides of the cabin and sighs before looking back over his shoulders."
    m "It has been a great experience."
    "I didn’t know whether it was truly a great experience."
    "For me, at least, I felt a bit used, but I still liked him regardless."
    "It was like spring turned into summer and then into autumn, just to fade into the midst of winter hidden by its crooked branches, which rather than death, indicated renewal of votes against a harsher winter next year."
    "A few minutes ago, the train had gone on its way with several paws sticking out of it, waving goodbye to the others who stayed, including me."
    "A white-furred paw sticking out of a window was swiftly pulled back inside the tram, and like that, only the thick smoke stayed behind."
    "As did I."
    "…"

        return