label day_1:
  show bedroom
  "The tender breeze intruded into the bedroom. As soon I woke up I felt the cold creep through me. Even though I fell asleep with all my bed sheets, I had somehow shoved them away to the floor during the night."
  "Half-naked, I tried to open one eye at a time.  Seamlessly, I felt the sunlight brush against my fur. It was quite messy from last night’s endeavor. Still, I wanted to rest a little bit more today."
  "But these last moments of morning had really been quiet, and the solitude of living semi-alone made it even harder not to think of releasing last  night’s stressful ruckus."
  "I was so tired that I hadn’t noticed the giant morning wood that had made its presence known. Like a tower, it stood leaning to the left like Pisa, except more fleshy and appetizing to the touch."
  "It dripped a small but significant amount of the natural lubricant soaked the tip, ready to be stroked. I needed a bit more foreplay though, and trying to stand up, I collapsed back in the comfort of the pillows that made my bed."
  "Hypnotized by my erection, all other things he planned for that morning slowly melted away, like butter on a hot pan.  All I could do was stare and think of how to treat myself accordingly."
  "Then it hit me, a simple relief was all I needed. I began searching for one of those sports magazines I bought the other day, innocently at the time. I later saw one of the pictures was of a snow leopard who had his shorts ripped by another teammate exposing his round, bubbly ass."
  "I wasn’t expecting it when I first opened the magazine, but it seems there was a section dedicated to mishaps like this one. For others, it was a reason to laugh at the professionals… It possibly was an affront to their image, but at this moment who cares?"
  "The magazine was easy to reach. It was just a few inches away from my bed, and locating the page where his exposed butt stood was even easier. I looked at my own erect cock, and I tried to sit up, struggling, but the continuous pumping of blood to my rock-solid dick was enough motivation to keep me awake and thinking of even more lewd things."
  "When I noticed the tip was already dried by the cold wind the open window produced, I considered a bit of lube wouldn’t hurt, but… the nearest pharmacy was a five-minute walk. I resorted to something gross, but it still worked. Spit was easy to get, and hey, it\\'s not like I needed much to get it working."
  "I still was disappointed that I didn’t have the courage to simply buy a porn magazine, but for the last three weeks or so, staring at this snow leopard’s shorts being ripped leaving his nude ass was enough for me to channel all my lustful thoughts."
  "Then, as the liquid that once moisturized my mouth dripped onto the tip of my cock, I pushed my foreskin up and down to spread it evenly. Almost ready, I considered perhaps looking at the other male figures that plastered the remainder of the sports magazine."
  "It makes one wonder if this was really made for people who had a more refined taste than me, but regardless, all other photos were modes, regretfully hiding their jewels and backside. Poor snow leopard… I don’t even know his name."
  "Going back to his accidental nakedness, I began stroking… up, down, up, down. A continuous movement that activated the most brutal and profane senses hidden within my flesh. More precum flooded the tip as I continued thrusting with my right paw holding the magazine ever so closely to my eyes, focused on his ass."
  "Time slowed down as each stroke distributed the blissful joy that pleasuring oneself with his own paw felt like. Lame as it may look from the outside, taking everything in and then out was the way I dealt with things."
  "Each delicate stroke felt more demanding. The thirst began to settle. Accelerating the rate of each stroke was only natural, and it made it easier to enjoy his twinkish body with all the grace that was the black spots amidst white fur on that round naked ass of his."
  "Then with a last up and down, my body contorted, and my penis spurted all its contents, jizz mixed with a pale substance which I concluded was the rest of the precum. The cum itself made its way up onto my chest and even my chin."
  "I kept going and going until there was nothing more left.  It started to just drip out of my tip, as I laid there, breathing hard. I had learned to keep myself quiet and disciplined, even when I was 100\% sure I was by myself."
  "Regardless, as I settled down, melting in my sheets once again with my paws still grabbing their respective item and organ, I noticed some streams of cum had made their way to my left side and were dripping a bit on my bed sheets."  
  "Standing up, I inspected the mess I had made. Merely eight shots were enough to soak my chest fur with cum, making it yet another successful but messy deed. It wasn’t like this always; waking up with a morning wood was rather annoying, but acting upon it was even rarer."
  "The worst part is always cleaning up the mess. I need to look presentable.  I want to make sure no one knows I have jizz in my fur {i}and am probably a pervert{/i}. Cleaning it has been an indispensable ritual. The risk of being spotted by wolves was such an awkward thought to keep in mind."
  "I walked to the bathroom and then turned the water on. At first the water was cold to the touch before becoming mildly warm. Perfect. I just needed a bit of fur shampoo and… Looking at the corner where I stored all the hygiene products, I noticed the lack of shampoo.  Only one of those cheap colognes was there."
  "{i}Shit, how am I supposed to clean this with only running water?{/i}"
  "{i}Huff… whatever.{/i}"
  "Turning off the showerhead and directing myself to the nearest towel, which didn’t look so great either, I dried my fur sloppily, missing several spots in the process. I was mainly concerned with removing the seed from me.  It stuck in clumps throughout my fur. Unfortunately, I had to tear those off as quickly as possible."
  "Finally free from my goofing around, I needed cologne to go outside and be {i}presentable{/i}."
  "But since the job involved heavy lifting, coming back home sweating was the rule, not the exception."
  "I never desired such a job, but leaving this damn town had become so difficult in the last few years.  I had become accustomed to the idea of working a low-paid job that I didn’t even like to begin with so I could pay the bills."
  "Anyway, looking at my wardrobe, there aren’t many options. Dirty laundry was thrown everywhere, as usual.  I figured that just casual attire would do for the day. It was Saturday anyway, and as much as I needed a day to rest, I had to face Mr. Sorim, my grumpy boss."
  "I never considered the possibility of being a lazy person until I moved on my own."
  "The moment I left Mom’s house just across the street, I felt a pang of anxiety in my chest. I never talked to anyone about it except him… Nemmi was always there to support me."
  "I always felt much closer to him. It was an unfathomable attraction, and dangerous propositions made my throat clog… I couldn’t speak to him again."
  "We kind of parted ways; we stopped talking to each other last year, but I yearned to speak to him again, see him again. I just couldn’t put it into words."
  "I never asked him if he was into men, like me, but regardless of the answer, he never seemed interested in either men or women."
  "He had a great record of being avoidant of topics pertaining to dating and liking people, which, thinking about it, both our families put greater pressure on both of us to marry intelligent, beautiful women."
  "Putting an extra emphasis on that, it\'s tough to imagine this town would ever grow out of its closeted ideas.  They were opposed to new ideas that flowed the world abroad, repulsed by the unknown that awaited us so anxiously."
  "Extinguishing those thoughts, I had told myself a thousand times not to be late to work, but it was already past noon once I finally put my clothes on, hoping no one would see past my facade that I had woken up and jerked off to a snow leopard’s butt who probably wasn’t happy to be so vulnerably exposed like that.  "
  "{i}Huff… Breathe in… Breathe out…{/i}"
  "Hurriedly preparing to exit after spraying the cologne and putting my shirt on, I heard a knock on the door."
  "Rushing to open it, I’m greeted by a familiar voice. Despite all my brain\'s efforts to ignore it, it was him."
  show nemmi pout short BlackHoodie 
  n t "Ehh, ehh, hello Erin."
  n  "I-I know it\'s been some time since we last saw each other."
  show nemmi -t pout short BlackHoodie "I couldn’t believe who was standing just a few inches from me, Nemmi, it was him, after more than one year and a month, he was simply back like that."
  e "Oh, hi Nemmi, I-, I’ve missed you greatly."
  n t "I’m sorry I’ve distanced myself in the last couple of months…"
  show nemmi -t pout short BlackHoodie
  e "It was one year and two months, Nemmi."
  e "Err, never mind!  Look, I know things may have been awkward back then, but-"
  n t "I just want things to go back to how they were! I didn’t tell you at that time, but Dad passed away, and I needed a bit of closure."
  show nemmi -t pout short BlackHoodie
  "All those days you two felt too uncomfortable to simply talk about things and ask commonplace questions like, How’s the weather had been explained the moment the words “passed away” was said."
  e "Oh{cps=2}...{/cps}"
  e "I’m sorry for your loss, but why didn’t you tell me the reason why you suddenly became so distant?  It was hard to keep in touch and everything suddenly changed."
  n t  "I wanted to tell you the reason! I mean, it’s too late now, but Mom got progressively worse, relying on alcohol and never letting me go out."
  n t "I basically became her servant."
  n t "In the last week or so, I couldn’t bear it anymore, and I finally forced her to go through rehab. It pains me to have lost not only one parent but both to this world’s addictions."
  show nemmi -t pout short BlackHoodie
  e "Oh, yeah, I think I heard some neighbors gossping about your mother. Damn, I’m so sorry, Nemmi."
  n t "It’s alright. I feel like I’ve been through hell and back."
  show nemmi -t pout short BlackHoodie
  "{cps=2}...{/cps}"
  "We stared at each other for a solid minute or so. I figured I would be even more late to work, but at this point, I didn’t care. Nemmi has been my childhood friend for nearly all my life."
  "All of the other children made fun of my fur pattern; being a snow leopard myself, I’d expected to be feared, but they used my only inherent attribute to make fun of me."
  "Then Nemmi came into action. He knew how much I suffered at the paws of those school bullies, having my tail pulled and my ears pulled as if to tear them apart. Nemmi put a halt to that, and he tightly held my paw that day. I felt strong by his side; he’d always keep me safe."
  "Well, if not for the fact that he was a bear, even bigger than average bears. I think people got the right message."
  "And so, we’d hang out every day. For once, I found myself a friend, someone I could rely on, and to the testament of time, we both carved our names in the oldest tree in City Central Park by the library."
  "The day he stopped hanging out with me, I felt lonely and even confused as to why Nemmi would throw everything away so suddenly. But I guess that explains it."
  n t "*Sigh* I’m sorry for all the pain I’ve caused by leaving you without an explanation. It has only recently come to my attention that my depression worsened things to such a degree that I couldn’t go out and-"
  show nemmi -t pout short BlackHoodie
  e "It’s ok Nemmi."
  e "I’ve missed you greatly, and now that you’re sort of back…"
  # chose go with him or not
  e "I don’t know how to mend things together. Look, let’s just hang out another day. Today, I’m already late to work."
  n t "Ahh…I’m sorry then-"
  show nemmi -t pout short BlackHoodie
  e "Don’t be. It’s just that nowadays I’ve been so busy and I...I really have to go; I’m the one who should be apologizing."
  "Another awkward silence followed my speech, as if I had built yet another wall to separate us. But I didn’t want that, I didn’t need another barrier, so why was I so afraid to skip work and hang out with him?"      
  n t "It’s ok. Can we hang out tomorrow?"
  show nemmi -t pout short BlackHoodie
  e "Sure, I guess I’ll be free tomorrow, since it’s Sunday."
  n t "Neat, then, see ya around."
  show nemmi -t pout short BlackHoodie
  "Nemmi took on a quicker pace when he left as if he had committed a great mistake by coming to my house, knocking on my door, and talking to me as if he expected something more."
  "I couldn’t stop noticing how uncomfortable he was, especially the moment I told him I was late for work…"
  "Did I prioritize a terrible job I don’t even like over a friend who I hadn’t seen in a long time?"
  "Maybe it’s for the best if we keep our thoughts secret from one another, or that he was such an asshole for holding an important bit of his secret from me, that his dad had died, and that his mother made things more difficult."
  "Regardless, I couldn’t help but feel sympathy, but the oddest thing was my total lack of reaction."
  "Maybe I felt like prolonging things would only result in another awkward moment, we needed to think alone, but I can’t help but wonder…"
  "{i}Why?{/i}"
  "Why didn’t Nemmi talk to me sooner?"
  "That was, sadly, a question that wouldn\'t be answered until tomorrow."
  "Getting distracted in my own thoughts, I didn’t notice Nemmi was long gone, and I had the entire day ahead of me. And walking down the steps of my front door, I see something thrown a few paces away."
  "A frail yet beautiful attempt at a bouquet of Myosotis, it was gently and tightly packed, held together by a red ribbon."
  "I thought it was cute at first, whoever had made that. Then I came to the realization it was probably Nemmi… But again, why all these vague signs?"
  "Did he want to say something? It was as if he had a knot in his throat the entire time like he was stepping on eggshells."  
  "As much as I wanted to lie to myself that I still knew him… I realized I no longer recognized the Nemmi I talked to just a few seconds ago."
  "Time seemed to dilate ever so slightly as the dimmed sunlight was obscured by the threat of rain."
  "Starting meekly, each droplet of water felt individually placed and inconsistent, too slow for anyone used to the rainy season."
  "It felt artificial, but independent of its nature, I was already late for work, so I shoved through all the confusing and bubbling emotions this eventful noon was and led my day as usual."
  "On the way to work, the uneven pavement that intersected this entire town alongside dirt paths always got mud in my boots. Since I didn’t want to make my house even more filthy, I had to resort to strange hops and jumps everywhere to avoid mud puddles."
  "Our town didn’t have many cars. Gasoline was a luxurious commodity around here. Only farmers had access to heavy machinery. As a means to connect us to the outside world, the train station linked us to the big cities, factories, and the rest of our country."
  "Lost in the mountains, our town even lacked a proper name. Thus, my parents, extended family, neighbors, and many others coined their own toponyms for this place forgotten in time and space."
  "..."
  "After three hours of hard work, lifting and rearranging some boxes for the local grocery store owned by Sorim, I felt tiredness surpassing every other will. Maybe I shouldn’t have masturbated so vigorously earlier."
  "Without a single warning, in the distance, I heard the train’s chimneys announcing its arrival. I remembered it had been three long years since the last time the outside world visited us."
  "Eagerly, I packed my things together and left a note for Mr. Sorim. I expected him to lash out at me for leaving the storage room so soon, but I couldn’t hide the excitement that washed over me."
  "Finally, news from the outside world. Finally, new people to see and converse with.  Finally, something new happens after three years in this place stuck in time."
  "Running to the train station, I stepped in all the puddles I had managed to avoid on the way to work. My shoes got soaked in muddy water, but the rain had stopped long ago, so I considered it fine."
  show trainstation
  "A crowd of 13 locals or so blocked the entrance of those leaving the train; nearly 50 people from abroad had made their way here."
  "I spotted some cousins and uncles among the crowd, but I managed to avoid them all altogether because I hated family drama.  Since my parents were already a wreck, I imagined my extended family was just as bad, if not worse.  I only wanted news about the outside world and possible means to leave this wretched town."
  "I’ve never seen so many different species in three years. There were those with giant ears, strange noses, and fur patterns so different from mine that I wondered if I had been transported to another world."
  "But in the crowd of chaos, someone rather tall, with a white fur complexion, a polar bear, stood somewhat confused and amazed at the simple visual of our town. Meanwhile, I felt a sting of compassion for him… Nah, I’ll admit, he was hot, and I wanted, no, needed to approach him first."
  "But before I did, I looked around to see if Nemmi was there by any chance.  Much to my disappointment, or rather relief, Nemmi was nowhere to be seen.  Even if I saw him, I think I would be hiding."
  "I didn’t want to lie to him or keep the false pretense that my work was more important. Now that I’m here, it seems like I’m doing a great deal of back stabbing to Nemmi. I felt a bit sorry for abandoning Nemmi, my childhood friend."
  "Regardless, I have no ties to Nemmi now.  Our lives are practically separated, and since he never even bothered to show up on my birthday, I figured that was the fracture point of our friendship."
  "But then he came back today… And I shoved him aside…"
  "No."
  "I can’t be seen doubting my own decisions, even if it hurts both of us… or if it only hurts Nemmi."
  "Snapping back to reality, I find myself struggling to free myself from the tensed-up crowd full of greetings, trivial conversations, and vague descriptions of news of the outside world."
  "Each one had a weird slate device that lit up whenever they tapped on it. I wondered why anyone would need such a piece of technology. One of them explained to me that it was a cell phone, but I decided to call it black slate regardless."
  "Raising my paw to catch the bear’s attention, I luckily managed to be noticed by him. He was a big, strong, tall polar bear. I was already fantasizing about dating him and was prepared to discover what this polar bear was doing in my town."
  "Almost falling face down next to him, the polar bear tightly embraced my left arm, standing me on my feet."
  show miq BlackSlacks WhiteDress 
  e  "Hi, oh, sorry, I just wanted to talk to you-..."
  show miq t BlackSlacks WhiteDress
  "???" "Mavoh… Semberelel."
  "???" "Bi laramye ayotidi Etye-Siril ?"
  show miq -t BlackSlacks WhiteDress
  "A huge gap formed between us. He spoke in a language so alien to my ears that I couldn’t stop thinking I somehow messed up everything.  I landed three more steps in the wrong direction, wanting to date him even though I didn’t even know his name."
  "Shit, How am I supposed to talk to him if we don’t speak the same language?"
  show miq t BlackSlacks WhiteDress
  "???" "Ah, sorry."
  show miq -t BlackSlacks WhiteDress
  "Snapping back to reality, a familiar set of words somehow made me think it was simply a misunderstanding, a mismatching of what language to use when traveling abroad."
  show miq t BlackSlacks WhiteDress
  "???" "Ah, I didn’t want you to fall, so are you alright?"
  show miq -t BlackSlacks WhiteDress
  e  "Yes!"
  e  "I mean, *cough* I’m fine. Thank you for helping me out."
  show miq t BlackSlacks WhiteDress
  "???" "Heh, no problem, kid."
  show miq -t BlackSlacks WhiteDress
  e  "Hey! I’m 20 years old, sir."
  show miq t BlackSlacks WhiteDress
  "???" "Ah, my apologies. It\'s time for me to stop using size to determine someone’s age."
  "???" "Also, a second apology for not introducing myself."
  show miq -t BlackSlacks WhiteDress
  "Somehow, I felt a tone of familiarity within his voice, like the taste of thick and sweet honey. If it weren’t for the fact that he was a polar bear, the coincidence of his voice reminding me of honey would have been weird, but I guess all bears must have a strong presence to intimidate people and bring them comfort."
  "If I had already known him previously, I didn’t remember, or this memory has been erased from my ever-growing library of memories.  When we both met each other\'s gaze when I stood up and looked at him, all I could think was how his eyes were a pond revealing his ever-elusive soul."
  "Then it hit me… we were still at the train station, looking at each other. Rather awkwardly, I tried saying something, but I had become a prisoner to silence."
  e  "Eh, my name’s Erin. Leif Erinson, but I prefer people call me Erin *chuckles*..."
  m t BlackSlacks WhiteDress "Ah, interesting. My name is Miqqailli, but most of my colleagues call me Miq. I’m an anthropology student at the National University of Berols."
  m "Judging by your confused expression when I spoke the common tongue, I guess it\'s not surprising you are unfamiliar since even to this day, you guys don’t know what a cellphone is."
  show miq -t BlackSlacks WhiteDress
  "With a lashing-out tone, I got a bitter taste of all the uncensored rudeness he exhaled while dressed so eloquently, as opposed to a simpleton like me."
  e  "Yeah, yeah… This town is basically stuck in time. We still use old technology. It happens to be more reliable, in my honest opinion."
  m t BlackSlacks WhiteDress "I see."
  m t BlackSlacks WhiteDress "Well, lead the way. I think it\'s a fair trade if we keep each other’s company so I don’t get lost."
  show miq -t BlackSlacks WhiteDress
  e  "Of course, Miq."
  m t BlackSlacks WhiteDress "There is no need to apologize. Right now, I’m simply a tourist, and you are my guide. I won’t forget to charge you for your generous presentative services, little one."
  show miq -t BlackSlacks WhiteDress
  e  "Ohh, right!"
  e  "So let’s first leave this crowded place. I can sense all the miasma in the air, infecting both of us with so much gossip and chatter."
  "I don’t know why such a weird set of words came out of my mouth. I guess I wanted to impress the bear, whom I wanted so much to have more than a chat with."
  "I must confess, he was hot and delectable to the homoerotic desires that so moved me. This city lacked an appropriate place to enjoy all the carnal desires of life."
  "and I conditioned myself to simply jerking off to that snow leopard’s booty earlier, but my mind quickly melted, and my lower brain turned on."
  "Not only did I want to satisfy my biological needs, I wanted to experience love, genuine love. With this polar bear, I think{cps=2}...{/cps} I got the best fish in the entire ocean."
  "To be completely honest, Nemmi was still a great candidate if I ever wanted to date someone and draw some kind of meaning out of it."
  "But regardless of what he said by my door, it still hurts me that he didn’t trust me with that information. If I had gotten more insight into his life at that time, I could’ve helped him, and we would be starting out the right way."
  "Thinking of Nemmi again made me realize how Nemmi made his presence omnipresent in my mind. The somber twink bear lied to me for years. For god’s sake, can’t I just forget him at least for the rest of today?"
  m t BlackSlacks WhiteDress "Hey! Erin, let’s go. We’re wasting our time here, so let’s be off quickly."
  show miq 
  e  "Sorry, I got distracted by my thoughts."
  m t BlackSlacks WhiteDress "Less thinking, more walking, my youngling; ahh, you have to show me around this town; it\'s almost like I’m visiting a century in the past."
  show miq -t BlackSlacks WhiteDress
  e  "Yes, let’s be off."
  "Quickly leading the large-built bear to the outside of the train station, exposing a bit of the known lore of the town I’ve been living in for the past 2 years or so... Actually this might not be enough time to know all of this city, but whatever, I keep going on about the lore my mom told me."
  scene park with dissolve 
  "We got to the central park, which was very empty that day. Despite the large number of tourists, it seemed they were much more interested in other affairs. We both sat by a large tree."
  "At least Miq and I could have a proper date..?"
  show miq BlackSlacks WhiteDress
  m  t BlackSlacks WhiteDress "So, just to be sure… I couldn’t stop thinking about it..."
  m  t BlackSlacks WhiteDress "Are you gay?"
  show miq -t BlackSlacks WhiteDress
  "Out of nowhere those words pierced me and broke my composture like a mirror shattering."
  e "Ah, what, oh..."
  e  "You mean liking men..?" 
  "{i}Of course idiot. Ruin this time and he's gone!{/i}"
  "Squeaking a response, I force myself to say it out loud, faking my mild discomfort at the inquiry."
  e "Yes, I am." 
  e "{i}I\'m gaayy~{/i}"
  m t BlackSlacks WhiteDress  "Ah, it took you long enough, hahaha!" 
  m t BlackSlacks WhiteDress "Very well, and so am I."
  show miq -t BlackSlacks WhiteDress
  "Nervously, I started to tense up a little bit. It was the first time I ever said that word and conformed to my sexual orientation in front of others."
  "It was liberating but also a bit unnerving. I didn’t know what that meant beyond, oh we both like men, so let’s go and fuck each other, am I right???"
  "But no, I had to settle my thoughts. Did I love him? Or was I lying to myself over the fact that he may be the only other gay person in this damned town in the middle of nowhere."
  "Then he cut through my thoughts as if tearing fabric apart."
  m t BlackSlacks WhiteDress  "Then, we should let loose a little bit since we both share the same liking."
  m t BlackSlacks WhiteDress "Do you mind if I take my shirt off?"
  show miq -t BlackSlacks WhiteDress
  e  "No, I don’t think people will mind it. I will also follow suit."
  m t BlackSlacks WhiteDress "Great!"
  show miq -t BlackSlacks WhiteDress
  "He quickly unbuttoned his shirt and loosened his tie. I did the same, but was immediately surrounded by a refreshing wind that brushed against my filthy, sweaty fur from all the work I did earlier lifting."
  m t BlackSlacks -WhiteDress "Can I hug you?"
  show miq -t BlackSlacks
  e  "Eh..."
  e  "Uhh, of course? let’s hug!"
  e  "I mean, it\'s not like I’ve been craving this for a long time-"
  "His tight embrace filled me with all I wanted at the moment… touch, warmth, and love. But to my surprise, I was also feeling… Conflicted with the whole situation. I then pulled away from his warm, comfortable belly."
  e  "I’m in a sort of weird situation at the moment, and you came out of nowhere, and we’re already hugging and everything.  Maybe we should go a wee bit slower?"
  m "Ah, don’t let yourself get fooled by these weird feelings, sweetie, let’s just enjoy the moment while it lasts."
  m "You don’t need to worry. Just live in it."
  show miq -t BlackSlacks
  e  "Right… Maybe I’m overthinking. It\\'s just that you’ve been so upfront about it that-"
  m "Shhh, it’s okay!  Back in my city, we have a much better appreciation of what means to be gay."
  m "Gay bars, nude clubs, gay saunas and much, much more. I go to at least one of those weekly."
  show miq -t BlackSlacks
  e  "Gay bars? What are those?"
  m "My poor child, a gay bar is a magical place. We, lovers of the masculine build, can hang out and talk about all kinds of things, including sex."
  m "It’s a place of liberation, one of the cornerstones of my own journey of self-discovery. When I was much younger, I went in one and simply snapped. Of course, I knew what I was doing and always went for safe sex."
  show miq -t BlackSlacks
  e  "I didn’t know those places existed. It must be a one-of-a-kind experience for you to be so open about your sexuality."
  "He noticed I wasn’t looking in his direction anymore. Instead, I was taking in a panorama view of what was in front of me: my very homophobic town, possibly full of closeted queers."
  m "Hey, it\\'s different for everyone. I can’t know or relate to your situation, but what I can do is be here to provide what you may need most.
  The moment those words came out of his mouth, I again felt comforted by his embrace, and my heart started to quieten its pace, returning to its regular beating."
  "I noticed I had been clinging to his exposed chest ever more, embracing him and playing with his nipples. Then I saw the bulge rising in his pants. Mine were getting ever so tight as well."
  m "Hehehe, you’re an eager one! You wanna see what’s hiding underneath these pants?"
  show miq -t BlackSlacks
  e  "Here? Out in the open?  We’re exposed!  Wouldn’t my house be a better place?"
  "Miq stood up first and then lifted me once I took his hand, shoving me into his exposed belly yet again. I could feel the ever-increasing erection tearing his underwear and his tight jeans that proudly displayed his bulge."
  "Boasting a giant smile, Miq posed like I was some king and he but a mere jester."
  m "Lead the way, my charming Erin."
  m "I never knew I would find someone so cute in my travels. You’re truly a brilliant piece among many who could never keep up with me."
  e  "Oh? Do you mean hookups?"
  m "Exactly, all of those men were a pain in the arse. All of them wanted to exploit me and my flesh..."
  m "I couldn’t help but feel like a piece of meat to satisfy those men and myself."
  m "But I hope we both can build something. Of course, I already like you as you are."
  e  "Hehehe, you’re making me embarrassed. I have never had someone say such odd things in one single day."
  m "I hope I’m not going against your own pace for things. I’m a bit desperate on matters of love."
  e  "But isn’t everyone a bit desperate about most things?"
  m "Hmm, maybe, maybe not. It’s a matter of going against the natural order of things, being against society as a whole, and yelling in the face of all those who have oppressed us."
  m "Spit on their face and tell them to fuck off! Because I won’t be dragged and trapped in their lies, just to be discarded in the road to become star-like."
  e  "Become a star?"
  m "It’s from a book I read a few months ago. It\\'s really insightful, but now’s not time to talk about books.  There are more urgent matters to attend to."
  "The rest of the trip back to my house was silent. Again, the awkward silence seemed to haunt me with uncomfortable feelings that I was doing something wrong, with layers of guilt and ignorance."
  "Finally we both finally got to my house. Much to my surprise, I then remembered my brother would be spending the week at mom’s house. Another great excuse to lay down with my bear and not have to worry about my brother shenanigans."
  "Hastily laying his luggage in the living room, we both headed directly to my stuffy bedroom."
  m "So this is your bedroom. It’s in quite a messy state, but I can bear this. I’ve been in filthier places myself."
  e  "Ah, sorry, I just never had the time to clean this mess. I never expected someone to join me for the night, so I threw my clothes everywhere."
  m "I don’t mind that."
  e  "Don’t be shy, make yourself at home. This mess can’t get any worse, ha ha ha..."
  m "Can I be completely naked then?"
  "Another request I never thought I’d hear. Given we’re both adults and maybe could get down to some fun being naked, why not?"
  "Already unfastening my pants, I let them fall to the ground. I was a bit hesitant to be naked in front of someone else for the first time. I just embraced his pace and removed my briefs."
  "Before he could react any further, I let myself be truly loose for once. Since he was laying on my bed, I needed to show him I was the master in this house. Falling onto his hefty frame, I kissed him.  Every time I parted his lips with mine, I wanted more, and more, and more."
  "I didn’t even take note that he was also naked from the beginning. Apparently once I started stripping down, he seized the opportunity to free himself from the confines of his pants. I started playing with nipples again, and the more I kissed him, the more our bodies seemed to melt into a single being."
  "The more we kissed, the more excited I got. I penetrated his mouth with my tongue, and he, mine.  I could taste his saliva all over my lips. It moistened my teeth, my tongue, my lips, and even some of my chin."
  "Finally, my hand made its way to his back, and we slowly began to embrace. I felt his backside and, eventually, his butt.  He quickly followed suit before deciding to lovingly bite my neck.  It was just the right amount of pressure to force me to moan."
  "My hands seemed to have a mind of their own, driven by wild instinct to touch, caress and explore all the parts of the polar bear’s nakedness.   He started thrusting into me, smearing his throbbing cock into mine.  We continued for a short time until I felt the urge to move forward.  I started to lick from his neck down his chest, playing a bit more with his nipples."
  "He moaned the entire time, perhaps due to pain from pinching his nipples, or maybe from pleasure.  His sensitive nips of his were amazingly fun to play with.  Before I knew it, I was back to kissing him and our saliva met yet again under one another’s lingual embrace."
  "We broke the sloppy kiss and gazed into each other’s eyes."
  e  "I like you, and I like where this is going~"
  m "I think you’re ready for this then..."
  m "I’ll be back in a second."
  "Breaking their cuddling frot session, he went back to the living room, naked as nature made us all, and ruffled in the luggage he brought."
  "There, he took out a bottle and a few packages of what looked like stickers with a round protrusion. He ripped one of those packages to reveal a condom, a rather thin condom, and a bottle, I assumed to contain lubricant."
  m "Here, take this, and let’s get down to business."
  e  "But I don’t know how to put one of these on."
  "He made a hand gesture for me to position my erect cock, and proceeded to dress my meat with the thinnest protection I could imagine. He took a bit of lube from the bottle and splashed it on the constrictive case that my cock was currently in."
  "After the impromptu sex ed lesson, he turned around, exposing his pulsating butthole. It looked so hungry, I wanted to fill it. I needed to! And so, I awkwardly positioned myself on top of him, trying my best to align my cock with his hole."
  "It felt… different than I expected once I slid into his ass.  The warm walls of his insides were comfortably hugging my dick, and so I started to thrust into him.  It was unlike simply jacking off; I lost track of my pace three times. Still, each thrust carried pleasure all over my body in a way I couldn’t put into words.  In fact, sentences and words became moans."
  "The language of sex… everyone knew what that meant. Thrust after thrust, I felt my rock-solid dick go in and out. I tried to be attentive to his moans as well.  It seemed he really loved receiving such a hard rod."
  "Though I’m at least 30 centimeters smaller than him in stature, I packed a huge meat.   Lost in the lust of the moment, though, those thoughts melted in meaning, and all that mattered at the moment was to keep banging him. I quickened my pace, and soon I felt the ultimate pleasure once I filled the condom with ropes of cum."
  "I didn’t want to pull out of him just yet, but I felt entirely drained of energy. It made me realize sex demands great physical strength and preparation. Stacking only a few boxes in the storage room tires me. Having sex for the first time was amazing, and though exhausted, it was a reward a million times better than money."
  "I slowly removed my still erect cock from his ass.  In the process, my condom fell into the darkness of my room.  It was quickly shoved aside by either Miq or me. I didn’t know who did it, and I didn’t care."
  "After the most incredible time of my life, I felt wasted. My cock slowly returned to its soft state, leaving me eager to try it once more. But I was tired and needed a good sleep after fucking him."
  "When I looked at him, I realized he was already snoring. I wondered if he even remained awake during the whole ordeal. While I was ready for another round, I didn’t think he would want to be penetrated during his hopefully sweet dreams."
  "With the bear occupying a large section of the bed, there was only a mere 30 centimeters’ width of bed left for me, and I worried I would fall from the bed.  Maybe he would hold me tight during our sleep like when we first cuddled together."
  "I tried to snuggle close to him.  He suddenly stopped snoring and, making a rough sound, rolled to the other side of the bed. Finally, he gave me a proper space to sleep."
  "And so I fell asleep, still wanting to talk to him.  I hoped we could finish our night on a more communicative note, something like: Woah dude, I didn’t know sex was this amazing! But it may be odd to talk about sex that way.  It may be best not to talk to him right now since he’s all sleepy, right?"
  "Maybe, tomorrow, we can talk more about things… about us."

jump day_2